services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    hostname: mongo_db
    volumes:
      - mongodb_data:/data/db/
      - mongodb_log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb_network
  qdrant:
    container_name: qdrant_db
    hostname: qdrant_db
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant_network
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: backend
    hostname: backend
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/app
          ignore:
            - ./data/
    networks:
      - qdrant_network
      - mongodb_network
    depends_on:
      - qdrant
      - mongo
volumes:
  qdrant_storage:
  mongodb_data:
  mongodb_log:
networks:
  mongodb_network:
  qdrant_network:
