services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    env_file:
      - .env.dev
    environment:
      - "MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}"
    ports:
      - "${PUBLIC_MINIO_CONSOLE_PORT}:9000"
      - "${PUBLIC_MINIO_PORT}:9001"
    volumes:
      - minio_data:/data

  mongo:
    container_name: mongo
    image: mongo:latest
    hostname: mongo
    env_file:
      - .env.dev
    ports:
      - "${PUBLIC_MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    env_file:
      - .env.dev
    ports:
      - "${PUBLIC_QDRANT_PORT}:6333"
      - "${PUBLIC_QDRANT_GRPC_PORT}:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  minio_data:
  mongodb_data:
  qdrant_data:
