services:
  mongo:
    image: mongo:latest
    hostname: mongo
    volumes:
      - mongodb_data:/data/db/
      - mongodb_log:/var/log/mongodb/
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - mongodb_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant_network

  minio:
    container_name: minio
    hostname: minio
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
    secrets:
      - minio_password
    volumes:
      - minio_data:/data
    networks:
      - minio_network
    env_file:
      - .env

  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongo:27017"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/app
          ignore:
            - ./data/
    networks:
      - qdrant_network
      - mongodb_network
volumes:
  qdrant_storage:
  mongodb_data:
  mongodb_log:
  minio_data:

networks:
  mongodb_network:
  qdrant_network:
  minio_network:
