services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db/
      - mongodb_log:/var/log/mongodb/
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - mongodb_network
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - qdrant_network
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongo:27017"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/app
          ignore:
            - ./data/
    networks:
      - qdrant_network
      - mongodb_network
    depends_on:
      - mongo
      - qdrant
volumes:
  qdrant_storage:
  mongodb_data:
  mongodb_log:
networks:
  mongodb_network:
  qdrant_network:
