services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - .env
    environment:
      MINIO_URL: "minio:9000"
      MONGODB_URL: "mongodb://mongo:27017"
    ports:
      - "${PUBLIC_BACKEND_PORT}:8080"

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "${PUBLIC_MINIO_CONSOLE_PORT}:9000"
      - "${PUBLIC_MINIO_PORT}:9001"
    volumes:
      - minio_data:/data

  mongo:
    container_name: mongo
    image: mongo:latest
    hostname: mongo
    env_file:
      - .env
    ports:
      - "${PUBLIC_MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "${PUBLIC_QDRANT_PORT}:6333"
      - "${PUBLIC_QDRANT_GRPC_PORT}:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  minio_data:
  mongodb_data:
  qdrant_data:
