services:
  minio:
    container_name: minio
    image: bitnami/minio:latest
    env_file:
      - .env
    networks:
      - net
    environment:
      - "MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}"
    ports:
      - "${PUBLIC_MINIO_CONSOLE_PORT}:9000"
      - "${PUBLIC_MINIO_PORT}:9001"
    volumes:
      - minio_data:/data

  mongo:
    container_name: mongo
    image: mongo:latest
    hostname: mongo
    env_file:
      - .env
    networks:
      - net
    ports:
      - "${PUBLIC_MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    env_file:
      - .env
    networks:
      - net
    ports:
      - "${PUBLIC_QDRANT_PORT}:6333"
      - "${PUBLIC_QDRANT_GRPC_PORT}:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  embedder:
    container_name: embedder
    depends_on:
      - qdrant
    image: ghcr.io/drop-table-team/embedder:latest
    env_file:
      - .env
    networks:
      - net
    environment:
      - "OLLAMA_ADDRESS=${OLLAMA_URL}"
      - "QDRANT_ADDRESS=http://qdrant:6334"
    ports:
      - "${PUBLIC_EMBEDDER_PORT}:8080"

  classic-search:
    container_name: classic-search
    depends_on:
      - qdrant
      - embedder
    image: ghcr.io/drop-table-team/classic-search:latest
    env_file:
      - .env
    networks:
      - net
    environment:
      - "MONGO_ADDRESS=mongodb://mongo:27017"
    ports:
      - "${PUBLIC_CLASSIC_SEARCH_PORT}:8080"

  llm-search:
    container_name: llm-search
    depends_on:
      - qdrant
      - embedder
    image: ghcr.io/drop-table-team/llm-search:latest
    env_file:
      - .env
    networks:
      - net
    environment:
      - "OLLAMA_ADDRESS=${OLLAMA_URL}"
      - "QDRANT_ADDRESS=http://qdrant:6334"
    ports:
      - "${PUBLIC_LLM_SEARCH_PORT}:8080"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - mongo
      - minio
      - embedder
    env_file:
      - .env
    networks:
      - net
    environment:
      - "BACKEND_OLLAMA_URL=${OLLAMA_URL}"
      - "MONGO_URI=mongodb://mongo:27017"
    ports:
      - "${PUBLIC_BACKEND_PORT}:8080"
    volumes:
      - ./example-config:/config
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    container_name: frontend
    depends_on:
      - backend
    image: ghcr.io/drop-table-team/frontend:latest
    env_file:
      - .env
    networks:
      - net
    ports:
      - "${PUBLIC_FRONTEND_PORT}:3000"

networks:
  net:

volumes:
  minio_data:
  mongodb_data:
  qdrant_data:
